<?php
/*------------------------------------------------------------------------
 # SNS Facebook - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$options         = $this->getConfigObject();
$likeBox 		 = $this->getLikebox();
?>
<?php if($options->pretext): ?>
<div class="pretext"><div><?php echo $options->pretext; ?></div></div>
<?php endif; ?>
<div class="block block-facebook" data-tablet="block block-facebook first">
	<div class="block-title"><?php echo $options->title; ?></div>
	<div class="block-content clearfix">
		<a class="btn-like" target="_blank" href="<?php echo $likeBox['info']['link'] ?>" title="<?php echo $likeBox['info']['name'] ?>"><i class="fa fa-thumbs-o-up"></i><?php echo $this->__(' Like us') ?></a>
		<div class="fanpage-info">
			<?php echo $likeBox['info']['likes'] ?> <?php echo $this->__('people like') ?> <a target="_blank" href="<?php echo $likeBox['info']['link'] ?>" title="<?php echo $likeBox['info']['name'] ?>"><?php echo $likeBox['info']['name'] ?></a>
		</div>
		<div class="fanpage-list">
			<?php echo $likeBox['list'];?>
		</div>
	</div>
</div>
<?php if($options->posttext): ?>
<div class="posttext"><div><?php echo $options->posttext; ?></div></div>
<?php endif; ?>

