<?php
$ajaxAction = 'ajaxgrid';
$options = $this->getConfigObject();
if( $options->list_products_by == 'order' ){
	$list = $this->getListByOrder();
} else {
	$list = $this->getListByCategory();
}

///Zend_Debug::dump($list); die;
$uq = rand().time();
?>
<?php if(!empty($list)){ ?>
<div class="sns-producttabs-wapper">
	<?php include 'scripts.phtml'; ?>
	<div id="sns_producttabs<?php echo $uq; ?>" class="sns-producttabs mrb50">
		<div class="sns-pdt-head">
			<!-- <h2><?php echo $options->title; ?></h2> -->
			<div class="sns-pdt-nav">
				<h3 class="pdt-nav">
					<?php foreach($list as $item){
					?>
					<span class="item-nav<?php echo (isset($item->active) && $item->active==1)?' first_load':''; ?>" 
						data-type="<?php echo $options->list_products_by; ?>"
						data-catid="<?php echo ($options->list_products_by == 'order')?"":$item->id ?>"
						data-orderby="<?php echo $item->orderid; ?>" data-href="pdt_<?php echo ($item->id == "*")?'all':$item->id; ?>">
						<span class="title-navi"><?php echo $item->title; ?>
						</span>
					</span>
					<?php } ?>
				</h3>
				<li class="dropdown pull-left tabdrop" style="display:none;" >
						<a href="#" data-toggle="dropdown" class="dropdown-toggle">
						<span class="display-tab"><?php echo $this->__('Tabs Product')  ?>   </span>
						</a>
					<ul class="dropdown-menu">
					<?php foreach($list as $item){
					?>
					<li class="item-nav<?php echo (isset($item->active) && $item->active==1)?' first_load':''; ?>" 
						data-type="<?php echo $options->list_products_by; ?>"
						data-catid="<?php echo ($options->list_products_by == 'order')?"":$item->id ?>"
						data-orderby="<?php echo $item->orderid; ?>" data-href="pdt_<?php echo ($item->id == "*")?'all':$item->id; ?>">
						<a class="title-navi"><?php echo $item->title; ?>
						</a>
					</li>
					
					<?php } ?>
				</ul>
				</li>
			</div>
			
			<?php if(isset($options->pretext) && !empty($options->pretext)) : ?>
				<p class="pretext"><?php echo $options->pretext;?></p>
			<?php endif; ?>
			
		</div>
		<div class="sns-pdt-container">
			<!--Begin Tab Nav -->
			
			<!-- End Tab Nav -->
			<!--Begin Tab Content -->
			<div class="sns-pdt-content">
				<?php $i = 0; foreach($list as $items) :
					$cls = (isset($items->active) && $items->active  == 1)?' ': '';
					$cls .= ($items->id == "*")?' pdt_all':' pdt_'.$items->id;
				?>
				<div class="pdt-content<?php echo $cls; ?>" >
					<div class="pdt-list products-grid<?php echo ' '.$options->effects; ?>">
					<?php /*
					<?php
						$i++;
						if($i==1){
							//include 'items.phtml';
						}else{ ?>
							<div class="content-loading"></div>
						<?php
						}
					?>
					*/ ?>
						<div class="content-loading"></div>
					</div>
					<div class="pdt-loadmore" data-href="pdt_<?php echo ($items->id == "*")?'all':$items->id; ?>"
					data-type="<?php echo $options->list_products_by; ?>"
					data-catid="<?php echo ($options->list_products_by == 'order')?"":$items->id ?>"
					data-orderby="<?php echo $items->orderid; ?>"
					data-all=""
					data-start="<?php echo $options->number_per_display;?>"
					data-loadnum="<?php echo $options->number_per_display;?>">
						<div class="btn-loadmore">
							<span class="loadmore button" 
							data-label="" 
							data-label-load=""></span>
						<?php if( $options->show_number_loadmore ):?>
							<span class="load-number" data-more=""
							data-total=""></span>
						<?php endif;?>
							<span class="ico-loading"></span>
						</div>
					</div>
				</div>
				<?php
				endforeach; ?>
			</div>
		</div>
		<!--End Tab Content -->
	</div>
</div>
<?php } else { echo '<p class="note-msg">' . $this->__('There are no products matching the selection.') . '</p>';}?>

