<?php
/*------------------------------------------------------------------------
 # SNS Products - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$themeConfig =   Mage::helper('lamino/data')->get();
$themeCfg =   Mage::helper('lamino/data');
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
$uniqued = rand().time();

$imgSize = Mage::helper('lamino/data')->getImgSize('L');
$imgWidth = 260;
$imgHeight = 343;
?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="sns_lider<?php echo $uniqued; ?>" class="block sns-slider sns-deals">
	<div class="slider-inner">
		    	<div class="block-title">
		    		<?php if($this->title!="") : ?>
		    			<strong><?php echo ($this->title);?></strong>
					<?php endif; ?>
		    	</div>

				    <div class="products-grid">
				    <?php foreach($_productCollection as $_product) : ?>
				    	<?php
					        $saleLabel = false;
					        $newLabel = false;
							$now = date("Y-m-d");
					        $newsFrom= substr($_product->getData('news_from_date'),0,10);
					        $newsTo=  substr($_product->getData('news_to_date'),0,10);
					        $price = $_product->getPrice();
					        $finalPrice = $_product->getFinalPrice();
					        if(!$newsTo && $newsFrom && $now>=$newsFrom) $newLabel = true;
					        if($newsTo && !$newsFrom && $now<=$newsTo) $newLabel = true;
							if ($now>=$newsFrom && $now<=$newsTo && $themeCfg->getField('general_useTagNew')){ 
								$newLabel = true;
							}
							if(isset($price) && isset($finalPrice) && $finalPrice < $price && $themeCfg->getField('general_useTagSale')) $saleLabel = true;
							
					        $endTime = Mage::getModel('core/date')->date("Y, m, d, H, i, s", $_product->getSpecialToDate());
						?>
						<?php if($now <= $endTime) : ?>
				        <div class="item">
							<div class="item-inner">
				        	<div class="row">
				        		<div class="col-xs-6 col-phone-12 item-img clearfix">
				                    <?php if ($newLabel) echo "<span class='ico-product ico-new'>New</span>"; ?>
			                        <div class="actions deals-action">
			                            <ul class="add-to-links">
			                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
			                                    <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" data-toggle="tooltip"  data-original-title="<?php echo $this->__('Add to Wishlist') ?>"><?php //echo $this->__('Add to Wishlist') ?></a></li>
			                                <?php endif; ?>
			                                <?php if($this->getAddToCompareUrl($_product)): ?>
			                                    <li><a title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $this->getAddToCompareUrl($_product) ?>" class="link-compare" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Compare') ?>"><?php //echo $this->__('Add to Compare') ?></a></li>
			                                <?php endif; ?>
			                            </ul>
										<div class="wrap-quickview">
											<div class="quickview-wrap">
												<a class="sns-btn-quickview" data-original-title="View" data-toggle="tooltip" href="<?php echo $_product->getProductUrl() ?>">
													<span><?php echo $this->__('View'); ?></span>
												</a>
											</div>
										</div>
			                        </div>
			                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
			                        	<span class="img-main">
											<img 
												data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" 
												src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" 
												alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</span>
			                        </a>
				        		</div>
				        		<div class="col-xs-6 col-phone-12">
			                        <div class="item-title">
			                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
			                        </div>
			                        <div class="desc">
			                        	<?php echo Mage::helper('core/string')->truncate($_product->getShortDescription(), 140); ?>
			                        </div>
			                        	
		                            <div class="rating">
		                            	<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
		                            </div>
		                            <div class="item-price">
		                                <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
				            			<?php if ($saleLabel) echo "<span class='ico-product ico-sale'>-".floor(100-($finalPrice/$price)*100)."%</span>"; ?>
		                            </div>
		                            
									<div class="countdown" data-endtime="<?php echo $endTime; ?>"></div>

		                            <?php if($_product->isSaleable()): ?>
		                                <button title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
		                            <?php else: ?>
		                                <span class="btn-cart out-of-stock" title="<?php echo $this->__('Out of stock') ?>" data-toggle="tooltip" data-original-title="<?php echo $this->__('Out of stock') ?>"><span><?php echo $this->__('Out of stock') ?></span></span>
		                            <?php endif; ?>
				        		</div>
				        	</div>
				        </div>
						</div>
				        <?php endif; ?>
				    <?php endforeach; ?>
				    </div>

	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
			singleItem: true,
			transitionStyle: 'backSlide',
            pagination: false,
            slideSpeed : 800,
            addClassActive: true,
			autoPlay: 8000
        });
    });
//]]>
</script>
<?php endif; ?>