<?php
/*------------------------------------------------------------------------
 # SNS Products - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$themeConfig =   Mage::helper('lamino/data')->get();
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
    $this->product_image_disp = false;
}
$uniqued = rand().time();

$imgSize = Mage::helper('lamino/data')->getImgSize('M');
$imgWidth = 100;
$imgHeight = 125;
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div id="sns_lider<?php echo $uniqued; ?>" class="block sns-slider<?php echo($this->effects)?' effect-'.$this->effects:'';?> column-style">
        <div class="slider-inner">
           <div class="block-title">
            <div class="title-navi">
                <?php if($this->title!="") : ?>
                    <strong><?php echo $this->title;?></strong>
                <?php endif; ?>
                 <div class="navslider">
                    <a class="prev" href="#"><i class="fa fa-angle-left"></i></a>
                    <a class="next" href="#"><i class="fa fa-angle-right"></i></a>
                </div>
            </div>      
        </div>

            <?php if($this->pretext): ?>
                <p><?php echo $this->pretext; ?></p>
            <?php endif; ?>

            <div class="container-slider">
                <div class="products-grid mini-products-list">
                    <?php
                    $i = 0;
                    foreach($_productCollection as $_product) : ?>
                        <?php
                        $i = $i+1;
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        $price = $_product->getPrice();
                        $finalPrice = $_product->getFinalPrice();
                        $class = '';
                        if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
                        if( isset($price) && isset($finalPrice) && $finalPrice < $price) $class .= ' have-icosale';
                        ?>
                        <?php if( ($i-1)%2 == 0 || $i-1 == 0):?>
                            <div class="item">
                        <?php endif; ?>
                        <div class="item-child">
                            <div class="item-inner clearfix<?php echo $class; ?>">
                                <div class="item-img">
                                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                        <span class="image-main">
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        </span>
                                    </a>
                                </div>
                                <div class="item-info">
                                    <div class="info-inner">
                                        <div class="item-title">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                                        </div>
                                       
                                        <div class="rating">
                                            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                                        </div>
                                         <div class="item-price">
                                            <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
                                       
                                            <div class="badges">
                                                <?php
                                                if ($now>=$newsFrom && $now<=$newsTo && $themeConfig['general_useTagNew']==1)
                                                    echo "<span class='ico-product ico-new'>New</span>";
                                                if (isset($price) && isset($finalPrice) && $finalPrice < $price && $themeConfig['general_useTagNew']==1)
                                                    echo "<span class='ico-product ico-sale'>-".floor(100-($finalPrice/$price)*100)." %</span>";
                                                ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div></div>
                        <?php if( $i%2 == 0 || $i == $_productCollection->count() ): ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>

                <?php if($this->posttext): ?>
                    <div class="posttext"><div><?php echo $this->posttext; ?></div></div>
                <?php endif; ?>

            </div>
        </div>
    </div>

<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
    $('#sns_lider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
        itemsCustom: [
            [0, 1],
            [480,2],
            [641,2]
        ],
        <?php if($this->auto){ ?>
        autoPlay: true,
        stopOnHover: true,
        <?php } ?>
        <?php if($this->duration){ ?>
        slideSpeed: <?php echo $this->duration; ?>,
        <?php } ?>
        pagination: false,
        slideSpeed : 800,
        addClassActive: true,
        afterAction: function (e) {
            if(this.$owlItems.length > this.options.items){
                $('#sns_lider<?php echo $uniqued; ?> .navslider').show();
            }else{
                $('#sns_lider<?php echo $uniqued; ?> .navslider').hide();
            }
        }
        //scrollPerPage: true,
    });
    $('#sns_lider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
        e.preventDefault();
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
    });
    $('#sns_lider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
        e.preventDefault();
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
    });
});
//]]>
</script>
<?php endif; ?>